# Generated by Django 2.2.4 on 2025-10-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=5),
        ),
    ]
