# Generated by Django 2.2.4 on 2025-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authors_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='sho ma badek', max_length=45),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
