# Generated by Django 2.2.4 on 2025-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20251008_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books_authors',
        ),
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='myapp.Books'),
        ),
    ]
