# Generated by Django 5.2.7 on 2025-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players_liked',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
