# Generated by Django 5.2.7 on 2025-10-19 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 19, 10, 47, 43, 220715)),
        ),
    ]
