# Generated by Django 5.2.7 on 2025-10-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_game_genere_remove_game_players_liked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genere',
        ),
        migrations.AddField(
            model_name='game',
            name='players_liked',
            field=models.ManyToManyField(related_name='liked_games', to='app.user'),
        ),
    ]
